version: '2'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
    volumes:
      - db-data:/var/log/mysql
  wordpress:
    depends_on:
      - db
    image: wordpress
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_PASSWORD=mypass
    volumes:
      - wp-data:/var/www/html
      - ./install-wp:/bin/install-wp
      - ./wp-cli.phar:/usr/local/bin/wp

volumes:
   db-data:
   wp-data: